name: desktop_multi_window_manager
description: A flutter plugin that combine window_manager and desktop_multi_window plugin together. thanks for MIXIN.org and leanflutter.org.
version: 0.0.1
homepage: https://github.com/769755893/desktop_window_manager

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterMultiWindowPlugin
      windows:
        pluginClass: DesktopMultiWindowPlugin